export const jsGlob = "**/*.?([cm])js?(x)"
export const tsGlob = "**/*.?([cm])ts?(x)"
export const jsxGlob = "**/*.?([cm])jsx"
export const tsxGlob = "**/*.?([cm])tsx"
export const astroGlob = "**/*.astro"
